"""Provider-neutral persistence for SQLite and PostgreSQL."""

from __future__ import annotations

import os
import re
import sqlite3
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional
from urllib.parse import parse_qs, urlsplit

from dotenv import load_dotenv

_BACKEND_DIR = Path(__file__).resolve().parent.parent
_ENV_FILE = _BACKEND_DIR / ".env"
load_dotenv(dotenv_path=_ENV_FILE, override=False)

DB_FILE = str(Path(__file__).resolve().with_name("sentinel.db"))
DEFAULT_DATABASE_SCHEMA = "sentinel_ai"
_POSTGRESQL_PREFIXES = ("postgresql://", "postgres://")
_SAFE_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_SECURE_SSL_MODES = {"require", "verify-ca", "verify-full"}

_SQLITE_TABLES = (
    """
    CREATE TABLE IF NOT EXISTS events (
        event_id TEXT PRIMARY KEY,
        timestamp TEXT,
        layer TEXT,
        entity_id TEXT,
        action TEXT,
        detail_json TEXT,
        source_confidence TEXT,
        attack_type TEXT,
        confidence_score REAL,
        is_simulated INTEGER
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS incidents (
        incident_id TEXT PRIMARY KEY,
        title TEXT,
        status TEXT,
        primary_entity TEXT,
        threat_score REAL,
        risk_level TEXT,
        data_json TEXT,
        updated_at TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS analyst_feedback (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        incident_id TEXT,
        event_id TEXT,
        feedback_type TEXT,
        notes TEXT,
        created_at TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS sandboxed_actions (
        action_id TEXT PRIMARY KEY,
        action_type TEXT,
        target_id TEXT,
        incident_id TEXT,
        status TEXT,
        message TEXT,
        timestamp TEXT
    )
    """,
)

_POSTGRESQL_TABLES = (
    (
        "events",
        """(
            event_id TEXT PRIMARY KEY,
            timestamp TEXT,
            layer TEXT,
            entity_id TEXT,
            action TEXT,
            detail_json TEXT,
            source_confidence TEXT,
            attack_type TEXT,
            confidence_score DOUBLE PRECISION,
            is_simulated BOOLEAN
        )""",
    ),
    (
        "incidents",
        """(
            incident_id TEXT PRIMARY KEY,
            title TEXT,
            status TEXT,
            primary_entity TEXT,
            threat_score DOUBLE PRECISION,
            risk_level TEXT,
            data_json TEXT,
            updated_at TEXT
        )""",
    ),
    (
        "analyst_feedback",
        """(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            incident_id TEXT,
            event_id TEXT,
            feedback_type TEXT,
            notes TEXT,
            created_at TEXT
        )""",
    ),
    (
        "sandboxed_actions",
        """(
            action_id TEXT PRIMARY KEY,
            action_type TEXT,
            target_id TEXT,
            incident_id TEXT,
            status TEXT,
            message TEXT,
            timestamp TEXT
        )""",
    ),
)


class _DatabaseConfigurationError(RuntimeError):
    def __init__(self, code: str) -> None:
        super().__init__(code)
        self.code = code


def _database_url() -> str:
    return os.getenv("DATABASE_URL", "").strip()


def _database_backend() -> str:
    database_url = _database_url().lower()
    if database_url.startswith(_POSTGRESQL_PREFIXES):
        return "postgresql"
    return "sqlite"


def _postgresql_schema() -> str:
    schema = os.getenv("DATABASE_SCHEMA", DEFAULT_DATABASE_SCHEMA).strip()
    schema = schema or DEFAULT_DATABASE_SCHEMA
    if not _SAFE_IDENTIFIER.fullmatch(schema):
        raise _DatabaseConfigurationError("invalid_schema")
    return schema


def _validate_postgresql_tls(database_url: str) -> None:
    try:
        query = parse_qs(urlsplit(database_url).query)
    except ValueError:
        raise _DatabaseConfigurationError("invalid_database_url") from None

    ssl_modes = query.get("sslmode", [])
    if not ssl_modes or ssl_modes[-1].lower() not in _SECURE_SSL_MODES:
        raise _DatabaseConfigurationError("tls_required")


def _load_psycopg() -> tuple[Any, Any, Any]:
    try:
        import psycopg
        from psycopg import sql
        from psycopg.rows import dict_row
    except ImportError:
        raise _DatabaseConfigurationError("driver_unavailable") from None
    return psycopg, sql, dict_row


@contextmanager
def _sqlite_connection() -> Iterator[sqlite3.Connection]:
    connection = sqlite3.connect(DB_FILE)
    connection.row_factory = sqlite3.Row
    try:
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


@contextmanager
def _postgresql_connection() -> Iterator[Any]:
    database_url = _database_url()
    _validate_postgresql_tls(database_url)
    psycopg, _, dict_row = _load_psycopg()
    connection = psycopg.connect(
        database_url,
        row_factory=dict_row,
        connect_timeout=10,
    )
    try:
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def _safe_error(error: BaseException) -> str:
    if isinstance(error, _DatabaseConfigurationError):
        return error.code

    message = str(error).lower()
    sqlstate = getattr(error, "sqlstate", None)

    if sqlstate in {"28000", "28P01"} or "authentication failed" in message:
        return "authentication_failed"
    if (
        "could not translate host name" in message
        or "getaddrinfo failed" in message
        or "name or service not known" in message
        or "temporary failure in name resolution" in message
        or "no such host is known" in message
    ):
        return "dns_resolution_failed"
    if "network is unreachable" in message or "no route to host" in message:
        if re.search(r"(?:[0-9a-f]{1,4}:){2,}", message):
            return "ipv6_unreachable"
        return "network_unreachable"
    if "timed out" in message or "timeout expired" in message:
        return "connection_timeout"
    if "connection refused" in message:
        return "connection_refused"
    if "ssl" in message or "tls" in message or "certificate" in message:
        return "tls_failed"
    if sqlstate == "42501" or "permission denied" in message:
        return "permission_denied"
    if "server closed the connection" in message:
        return "connection_lost"
    return "database_unavailable"


def _qualified_table(sql: Any, schema: str, table: str) -> Any:
    return sql.SQL("{}.{}").format(sql.Identifier(schema), sql.Identifier(table))


def _init_sqlite() -> None:
    with _sqlite_connection() as connection:
        for statement in _SQLITE_TABLES:
            connection.execute(statement)


def _init_postgresql(schema: str) -> None:
    _, sql, _ = _load_psycopg()
    with _postgresql_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(
                    sql.Identifier(schema)
                )
            )
            for table_name, columns in _POSTGRESQL_TABLES:
                cursor.execute(
                    sql.SQL("CREATE TABLE IF NOT EXISTS {}.{} {}").format(
                        sql.Identifier(schema),
                        sql.Identifier(table_name),
                        sql.SQL(columns),
                    )
                )


def _raise_operation_error(
    backend: str,
    operation: str,
    error: BaseException,
) -> None:
    category = _safe_error(error)
    raise RuntimeError(
        f"{backend.capitalize()} database {operation} failed ({category})."
    ) from None


def init_db() -> None:
    """Create the persistence schema without deleting or replacing existing data."""
    backend = _database_backend()
    schema: Optional[str] = "main" if backend == "sqlite" else None
    try:
        if backend == "postgresql":
            schema = _postgresql_schema()
            _init_postgresql(schema)
        else:
            _init_sqlite()
    except Exception as error:
        get_database_status._last_status = {
            "backend": backend,
            "connected": False,
            "schema": schema,
            "error": _safe_error(error),
        }
        _raise_operation_error(backend, "initialization", error)

    get_database_status._last_status = {
        "backend": backend,
        "connected": True,
        "schema": schema,
        "error": None,
    }


def save_feedback(
    feedback_type: str,
    incident_id: str,
    event_id: Optional[str],
    notes: str,
    created_at: str,
) -> None:
    backend = _database_backend()
    try:
        if backend == "postgresql":
            _, sql, _ = _load_psycopg()
            schema = _postgresql_schema()
            with _postgresql_connection() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        sql.SQL(
                            """
                            INSERT INTO {} (
                                incident_id, event_id, feedback_type, notes, created_at
                            ) VALUES (%s, %s, %s, %s, %s)
                            """
                        ).format(_qualified_table(sql, schema, "analyst_feedback")),
                        (incident_id, event_id, feedback_type, notes, created_at),
                    )
        else:
            with _sqlite_connection() as connection:
                connection.execute(
                    """
                    INSERT INTO analyst_feedback (
                        incident_id, event_id, feedback_type, notes, created_at
                    ) VALUES (?, ?, ?, ?, ?)
                    """,
                    (incident_id, event_id, feedback_type, notes, created_at),
                )
    except Exception as error:
        _raise_operation_error(backend, "write", error)


def log_sandboxed_action(
    action_id: str,
    action_type: str,
    target_id: str,
    incident_id: str,
    status: str,
    message: str,
    timestamp: str,
) -> None:
    backend = _database_backend()
    values = (
        action_id,
        action_type,
        target_id,
        incident_id,
        status,
        message,
        timestamp,
    )
    try:
        if backend == "postgresql":
            _, sql, _ = _load_psycopg()
            schema = _postgresql_schema()
            with _postgresql_connection() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        sql.SQL(
                            """
                            INSERT INTO {} (
                                action_id, action_type, target_id, incident_id,
                                status, message, timestamp
                            ) VALUES (%s, %s, %s, %s, %s, %s, %s)
                            """
                        ).format(_qualified_table(sql, schema, "sandboxed_actions")),
                        values,
                    )
        else:
            with _sqlite_connection() as connection:
                connection.execute(
                    """
                    INSERT INTO sandboxed_actions (
                        action_id, action_type, target_id, incident_id,
                        status, message, timestamp
                    ) VALUES (?, ?, ?, ?, ?, ?, ?)
                    """,
                    values,
                )
    except Exception as error:
        _raise_operation_error(backend, "write", error)


def get_sandboxed_actions() -> List[Dict[str, Any]]:
    backend = _database_backend()
    try:
        if backend == "postgresql":
            _, sql, _ = _load_psycopg()
            schema = _postgresql_schema()
            with _postgresql_connection() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        sql.SQL("SELECT * FROM {} ORDER BY timestamp DESC").format(
                            _qualified_table(sql, schema, "sandboxed_actions")
                        )
                    )
                    rows = cursor.fetchall()
        else:
            with _sqlite_connection() as connection:
                rows = connection.execute(
                    "SELECT * FROM sandboxed_actions ORDER BY timestamp DESC"
                ).fetchall()
    except Exception as error:
        _raise_operation_error(backend, "read", error)

    return [dict(row) for row in rows]


def get_database_status() -> Dict[str, Any]:
    """Return metadata for the last verified initialization attempt."""
    backend = _database_backend()
    schema: Optional[str] = "main" if backend == "sqlite" else None

    if backend == "postgresql":
        try:
            schema = _postgresql_schema()
        except Exception as error:
            return {
                "backend": backend,
                "connected": False,
                "schema": None,
                "error": _safe_error(error),
            }

    last_status = getattr(get_database_status, "_last_status", None)
    if (
        last_status is not None
        and last_status["backend"] == backend
        and last_status["schema"] == schema
    ):
        return dict(last_status)

    return {
        "backend": backend,
        "connected": False,
        "schema": schema,
        "error": "not_initialized",
    }
