import React, { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, ShieldAlert, CheckCircle2, Info, X, Bell } from 'lucide-react';
import { cn } from './cn';

/**
 * Notification / alerting system.
 *
 * Provides a single source of truth for admin alerts. A `notify()` call
 * both pushes a transient toast (auto-dismisses) and appends to a
 * persistent alert log surfaced by the Navbar notification center.
 */

const NotificationContext = createContext(null);

const SEVERITY_META = {
  critical: { icon: ShieldAlert, accent: '#9F1239', soft: 'bg-rose-50', text: 'text-rose-700', border: 'border-l-rose-600' },
  danger:   { icon: AlertTriangle, accent: '#C43D4B', soft: 'bg-rose-50', text: 'text-rose-700', border: 'border-l-rose-500' },
  warning:  { icon: AlertTriangle, accent: '#B7791F', soft: 'bg-amber-50', text: 'text-amber-700', border: 'border-l-amber-500' },
  success:  { icon: CheckCircle2, accent: '#16805C', soft: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-l-emerald-500' },
  info:     { icon: Info, accent: '#2563EB', soft: 'bg-blue-50', text: 'text-blue-700', border: 'border-l-blue-500' },
};

let _id = 0;
const nextId = () => `ntf-${Date.now()}-${_id++}`;

export function NotificationProvider({ children }) {
  const [alerts, setAlerts] = useState([]);   // persistent log
  const [toasts, setToasts] = useState([]);   // transient
  const [lastReadAt, setLastReadAt] = useState(Date.now());
  const timers = useRef(new Map());

  const dismissToast = useCallback((id) => {
    setToasts((t) => t.filter((x) => x.id !== id));
    const timer = timers.current.get(id);
    if (timer) {
      clearTimeout(timer);
      timers.current.delete(id);
    }
  }, []);

  const notify = useCallback(
    ({ severity = 'info', title, message, ttl = 6000 }) => {
      const id = nextId();
      const entry = { id, severity, title, message, ts: Date.now() };
      setAlerts((a) => [entry, ...a].slice(0, 60));
      setToasts((t) => [entry, ...t].slice(0, 4));
      if (ttl > 0) {
        const timer = setTimeout(() => dismissToast(id), ttl);
        timers.current.set(id, timer);
      }
      return id;
    },
    [dismissToast]
  );

  useEffect(() => {
    const map = timers.current;
    return () => map.forEach((t) => clearTimeout(t));
  }, []);

  // Poll backend for alerts generated by the detection engine
  useEffect(() => {
    let cancelled = false;
    const poll = async () => {
      try {
        const res = await fetch('/api/alerts?limit=60');
        if (!res.ok || cancelled) return;
        const data = await res.json();
        if (data.alerts && data.alerts.length > 0) {
          setAlerts((prev) => {
            const ids = new Set(prev.map((a) => a.id));
            const fresh = data.alerts
              .filter((a) => !ids.has(a.id))
              .map((a) => ({ ...a, ts: typeof a.ts === 'string' ? new Date(a.ts).getTime() : a.ts }));
            if (fresh.length === 0) return prev;
            // Fire toasts for new critical/danger alerts
            fresh.forEach((a) => {
              if (a.severity === 'critical' || a.severity === 'danger') {
                const id = a.id;
                setToasts((t) => [a, ...t].slice(0, 4));
                const timer = setTimeout(() => dismissToast(id), 6000);
                timers.current.set(id, timer);
              }
            });
            return [...fresh, ...prev].slice(0, 60);
          });
        }
      } catch (e) {
        // silent - backend may not be running
      }
    };
    poll();
    const interval = setInterval(poll, 8000);
    return () => { cancelled = true; clearInterval(interval); };
  }, [dismissToast]);

  const unreadCount = useMemo(
    () => alerts.filter((a) => a.ts > lastReadAt).length,
    [alerts, lastReadAt]
  );

  const value = useMemo(
    () => ({
      alerts,
      toasts,
      unreadCount,
      notify,
      dismissToast,
      markAllRead: () => setLastReadAt(Date.now()),
      clearAlerts: () => setAlerts([]),
    }),
    [alerts, toasts, unreadCount, notify, dismissToast]
  );

  return (
    <NotificationContext.Provider value={value}>
      {children}
      <ToastViewport toasts={toasts} onDismiss={dismissToast} />
    </NotificationContext.Provider>
  );
}

export function useNotifications() {
  const ctx = useContext(NotificationContext);
  if (!ctx) throw new Error('useNotifications must be used within NotificationProvider');
  return ctx;
}

function ToastViewport({ toasts, onDismiss }) {
  return (
    <div className="toast-viewport">
      {toasts.map((t) => {
        const meta = SEVERITY_META[t.severity] || SEVERITY_META.info;
        const Icon = meta.icon;
        return (
          <div
            key={t.id}
            className={cn('toast-card animate-slideInRight p-3 flex items-start gap-3', meta.border)}
            role="alert"
          >
            <div className={cn('shrink-0 rounded-lg p-1.5', meta.soft)}>
              <Icon className="w-4 h-4" style={{ color: meta.accent }} />
            </div>
            <div className="min-w-0 flex-1">
              <p className="text-xs font-bold text-slate-900 truncate">{t.title}</p>
              {t.message && <p className="text-[11px] text-slate-600 mt-0.5 leading-snug">{t.message}</p>}
            </div>
            <button
              onClick={() => onDismiss(t.id)}
              className="shrink-0 text-slate-400 hover:text-slate-700 transition"
              aria-label="Dismiss notification"
            >
              <X className="w-3.5 h-3.5" />
            </button>
          </div>
        );
      })}
    </div>
  );
}

/** Formats a timestamp as a compact relative label ("just now", "3m", ...). */
export function relativeTime(ts) {
  const s = Math.floor((Date.now() - ts) / 1000);
  if (s < 5) return 'just now';
  if (s < 60) return `${s}s ago`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  return `${h}h ago`;
}

export { SEVERITY_META, Bell };
